### ISSUE TITLE
Customization bug

### ISSUE THREAD

**Issue by maria9290** [jujoco/Twitch-chatbot-multitask-task-list-overlay#1]
JavaScript error message for configs:
Line: 11
Char: 2
Error: Expected identifier, string or number
Code: 800A0404
Source: Microsoft JScript compilation error

**Comment by jujoco** [comment]
Hi @maria9290, 

I'm working on releasing a YouTube video demonstrating the setup process.

But looks like the error message is indicating that ine 11 in the configs.js file is written incorrectly.

line 10: USERNAME should be surrounded by double quotes followed by a comma.
line 11: should still the closing curly brece followed by a comma.
```
7:    auth: {
8:  		twitch_oauth: "OAUTHTOKEN", // Replace OAUTHTOKEN with your Twitch oauth token
9:		twitch_channel: "CHANNEL", // Replace CHANNEL with a Twitch channel name
10:		twitch_username: "USERNAME",  <-- example: "jujoco"
11:   },
```
